### ISSUE TITLE
Semi-relevant TODO List 

### ISSUE THREAD

**Issue by sanko** [sanko/Fl.pm#1]
# Known bugs
- [x] Major reference related bug
  - [x] Tested on Fl::Input locally; need to port to other widgets
- [ ] No support for custom widgets
  - [ ] Documentation
  - [ ] Examples
  - [x] Basic Implementation (draw and handle)
  - [ ] Advanced Implementation (all protected methods)
- [x] Say 'goodbye' to xs=>cpp and say goodbye to messy, template based code
- [ ] App icons
  - [ ] Linux
  - [ ] [Windows](http://seriss.com/people/erco/fltk/howto-windows-app-icon.html)
  - [ ] OSX
- [ ] PAR
# Supported Widgets
- [x] Fl::Adjuster
- [x] Fl::Box
- [ ] Fl::Browser
- [x] Fl::Button
- [x] Fl::Chart
- [ ] Fl::CheckBrowser
- [x] Fl::CheckButton
- [ ] Fl::Choice
- [ ] Fl::Clock
- [ ] Fl::ColorChooser
- [ ] Fl::CopySurface
- [x] Fl::Counter
- [ ] Fl::Device
- [x] Fl::Dial
- [ ] Fl::DoubleWindow
- [ ] Fl::FileBrowser
- [ ] Fl::FileChooser
- [ ] Fl::FileIcon
- [ ] Fl::FileInput
- [x] Fl::FillDial
- [x] Fl::FillSlider
- [x] Fl::FloatInput
- [ ] Fl::GIFImage
- [ ] Fl::GlWindow
- [x] Fl::Group
- [ ] Fl::HelpDialog
- [ ] Fl::HelpView
  - [ ] subclass to support http, etc. in get_image(...)
- [ ] Fl::HoldBrowser
- [x] Fl::HorFillSlider
- [x] Fl::HorNiceSlider
- [x] Fl::HorSlider
- [x] Fl::HorValueSlider
- [ ] Fl::Image
- [ ] Fl::ImageSurface
- [x] Fl::Input
- [x] Fl::InputChoice
- [x] Fl::IntInput
- [x] Fl::LightButton
- [x] Fl::LineDial
- [x] Fl::Menu
- [ ] Fl::MenuBar
- [x] Fl::MenuButton
- [ ] Fl::MenuItem
- [ ] Fl::MenuWindow
- [x] Fl::MultilineInput
- [x] Fl::MultilineOutput
- [ ] Fl::MultiBrowser
- [ ] Fl::MultiLabel
- [ ] Fl::NativeFileChooser
- [x] Fl::NiceSlider
- [ ] Fl::Object
- [x] Fl::Output
- [ ] Fl::OverlayWindow
- [ ] Fl::Pack
- [ ] Fl::PagedDevice
- [ ] Fl::Pixmap
- [ ] Fl::Plugin
- [ ] Fl::PNGImage
- [ ] Fl::PNMImage
- [ ] Fl::Positioner
- [ ] Fl::Preferences
- [x] Fl::Progress
- [x] Fl::RadioButton
- [x] Fl::RadioLightButton
- [x] Fl::RadioRoundButton
- [x] Fl::RepeatButton
- [x] Fl::ReturnButton
- [x] Fl::Roller
- [x] Fl::RoundButton
- [ ] Fl::RoundClock
- [ ] Fl::Scroll
- [x] Fl::Scrollbar
- [x] Fl::SecretInput
- [ ] Fl::SelectBrowser
- [ ] Fl::showcolormap
- [x] Fl::SimpleCounter
- [ ] Fl::SingleWindow
- [x] Fl::Slider
- [ ] Fl::Spinner
- [ ] Fl::SysMenuBar
- [ ] Fl::Table
- [ ] Fl::TableRow
- [x] Fl::Tabs
- [ ] Fl::TextBuffer
- [ ] Fl::TextDisplay
- [ ] Fl::TextEditor
- [ ] Fl::Tile
- [ ] Fl::TiledImage
- [ ] Fl::Timer
- [ ] Fl::ToggleButton
- [ ] Fl::ToggleLightButton
- [ ] Fl::ToggleRoundButton
- [ ] Fl::Tooltip
- [ ] Fl::Tree
- [ ] Fl::TreeItem
- [ ] Fl::TreeItemArray
- [ ] Fl::TreePrefs
- [x] Fl::Valuator
- [x] Fl::ValueInput
- [x] Fl::ValueOutput
- [x] Fl::ValueSlider
- [ ] Fl::Widget
  - [x] Code
  - [ ] Documentation
- [x] Fl::Window
- [ ] Fl::Wizard
